travis:
  secure:
    BINSTAR_TOKEN: KWUAYIsT0ubT64YH86vRWt7sCPrRlf3ILBr77FKkECPkBL6+cNfDs4L/ygcQqAq1on3GF3U2fbh742BDhj8q8AXaWf8SusR7Wvzsn1uVQT57yEqKHQhGAbtAOIIFYd9yykVYRyJp0Gcv1g57FcWk2VIRaIF0yPMMKRMDcpy49DmxWuGLb/iFMF/E9nqcRkKVQP3b5pjlVoOeSygQiFTYUXc8KbM3XwucpkXYR9PqNDwtgKIKTUDh5a5BZpgQUF3x/MZU6SqzA6xUR7b2I3OU0j28IXIw2HF31tt1K7+Ul01iFVkFUKBoCzhP6Wmah4y5nYv0D0pTH8MCGX+RaT4nw99oMN9yyeVjaeG8GaB8WFn07hfsut4xbd5QqZR7PEvqtKXRIkLBRRT4ZsOkApVAsVb7RM4VKx5gc783ewba10M67T4pHJAn2h9MxlJbBWHYuN/aKrfTQ/M+7mh0qP/zuGP0LY2D9EEiDK/zO2v3hn0/ETPNySse4WxuYzGnlRiHP8A2W19/z8/P0p/+Hu6VOo/tsMvzQyVGX32CIEmHU6V2nSJO6MAzcnfDkPGkfiJ/TYDVT0NAlxnNiyvr61rzCs1hrqLsMvAYTwghlFnBBIyw2PyAv5Z2tBxTYUv5D8/WotD4fyUtfutfR8kvarDotGYWr4+5KBniSyXUpAnuGgA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
